import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { validateXML } from 'xmllint-wasm'

import { buildPain001, formatAmount, sepaText, type BatchTransaction, type Pain001Input } from './pain001'
import type { PaymentPlan } from './types'

/** Official ISO 20022 schema, generated by the ISO Standards Editor (2019). */
const XSD = readFileSync(join(__dirname, '../../../supabase/tests/fixtures/pain.001.001.09.xsd'), 'utf8')

async function assertSchemaValid(xml: string) {
  const result = await validateXML({
    xml: { fileName: 'payment.xml', contents: xml },
    schema: { fileName: 'pain.001.001.09.xsd', contents: XSD },
  })
  expect(result.errors.map((e) => e.rawMessage)).toEqual([])
  expect(result.valid).toBe(true)
}

function plan(over: Partial<PaymentPlan> = {}): PaymentPlan {
  return {
    route: 'sepa',
    currency: 'EUR',
    amount_cents: 121_000,
    creditor_name: 'Acme SL',
    creditor_iban: 'ES9121000418450200051332',
    reference: null,
    requested_execution_date: '2026-09-30',
    ...over,
  }
}

function tx(id: string, over: Partial<PaymentPlan> = {}, remittance = `Factura ${id}`): BatchTransaction {
  return { end_to_end_id: id, plan: plan(over), remittance_text: remittance }
}

function input(transactions: BatchTransaction[], over: Partial<Pain001Input> = {}): Pain001Input {
  return {
    message_id: 'IA-20260921-0001',
    created_at: new Date('2026-09-21T09:15:30.123Z'),
    debtor: { name: 'Vidal Consulting GmbH', iban: 'CH9300762011623852957', bic: null },
    transactions,
    ...over,
  }
}

describe('pain.001.001.09 — schema validity', () => {
  it('a single SEPA transfer validates against the official ISO XSD', async () => {
    await assertSchemaValid(buildPain001(input([tx('E2E-1')])))
  })

  it('a mixed file (SEPA EUR + Swiss QRR + SCOR, two dates) validates', async () => {
    const xml = buildPain001(
      input([
        tx('E2E-1'),
        tx('E2E-2', { requested_execution_date: '2026-10-01', reference: { kind: 'SCOR', value: 'RF18539007547034' } }),
        tx('E2E-3', {
          route: 'ch_domestic',
          currency: 'CHF',
          creditor_name: 'Müller & Söhne AG',
          creditor_iban: 'CH4431999123000889012',
          reference: { kind: 'QRR', value: '210000000003139471430009017' },
        }),
      ]),
    )
    await assertSchemaValid(xml)
  })

  it('the validator is not vacuous: a file with elements out of order is rejected', async () => {
    const good = buildPain001(input([tx('E2E-1')]))
    const swapped = good.replace(
      /(<Dbtr>.*?<\/Dbtr>)(<DbtrAcct>.*?<\/DbtrAcct>)/,
      '$2$1',
    )
    expect(swapped).not.toBe(good)
    const result = await validateXML({
      xml: { fileName: 'payment.xml', contents: swapped },
      schema: { fileName: 'pain.001.001.09.xsd', contents: XSD },
    })
    expect(result.valid).toBe(false)
  })

  it('validates with a debtor BIC', async () => {
    await assertSchemaValid(
      buildPain001(input([tx('E2E-1')], { debtor: { name: 'Vidal', iban: 'CH9300762011623852957', bic: 'UBSWCHZH80A' } })),
    )
  })

  it('stays valid when names contain XML-significant characters', async () => {
    const xml = buildPain001(input([tx('E2E-1', { creditor_name: 'A&B <Servicios> "Ñandú" SL', route: 'ch_domestic', currency: 'CHF', creditor_iban: 'CH9300762011623852957' })]))
    expect(xml).toContain('A&amp;B &lt;Servicios&gt; &quot;Ñandú&quot; SL')
    await assertSchemaValid(xml)
  })
})

describe('pain.001.001.09 — content', () => {
  const xml = buildPain001(
    input([
      tx('E2E-1'),
      tx('E2E-2', { amount_cents: 5 }),
      tx('E2E-3', { route: 'ch_domestic', currency: 'CHF', creditor_iban: 'CH9300762011623852957', amount_cents: 99_999 }),
    ]),
  )

  it('group header totals match the transactions exactly', () => {
    expect(xml).toContain('<NbOfTxs>3</NbOfTxs>')
    // 1210.00 + 0.05 + 999.99
    expect(xml).toContain('<CtrlSum>2210.04</CtrlSum>')
  })

  it('makes one payment block per route, currency and date, each with its own control sum', () => {
    const blocks = xml.match(/<PmtInf>.*?<\/PmtInf>/g) ?? []
    expect(blocks).toHaveLength(2)
    expect(blocks[0]).toContain('<CtrlSum>999.99</CtrlSum>') // ch_domestic sorts first
    expect(blocks[1]).toContain('<CtrlSum>1210.05</CtrlSum>')
  })

  it('marks SEPA blocks with the SEPA service level and SLEV charges, and Swiss blocks with neither', () => {
    const blocks = xml.match(/<PmtInf>.*?<\/PmtInf>/g) ?? []
    expect(blocks[1]).toContain('<SvcLvl><Cd>SEPA</Cd></SvcLvl>')
    expect(blocks[1]).toContain('<ChrgBr>SLEV</ChrgBr>')
    expect(blocks[0]).not.toContain('SEPA')
    expect(blocks[0]).not.toContain('ChrgBr')
  })

  it('drops milliseconds from the creation time', () => {
    expect(xml).toContain('<CreDtTm>2026-09-21T09:15:30Z</CreDtTm>')
  })

  it('writes an unknown debtor bank as NOTPROVIDED', () => {
    expect(xml).toContain('<Othr><Id>NOTPROVIDED</Id></Othr>')
  })
})

describe('pain.001.001.09 — guards', () => {
  it('refuses an empty file', () => {
    expect(() => buildPain001(input([]))).toThrow(/at least one/)
  })

  it('refuses duplicate end-to-end ids', () => {
    expect(() => buildPain001(input([tx('SAME'), tx('SAME')]))).toThrow(/Duplicate EndToEndId/)
  })

  it('refuses ids longer than 35 characters or with forbidden characters', () => {
    expect(() => buildPain001(input([tx('x'.repeat(36))]))).toThrow(/1–35/)
    expect(() => buildPain001(input([tx('bad&id')]))).toThrow(/1–35/)
  })

  it('refuses non-integer or non-positive amounts', () => {
    expect(() => formatAmount(0)).toThrow()
    expect(() => formatAmount(12.5)).toThrow()
    expect(() => formatAmount(-100)).toThrow()
  })
})

describe('amounts and text', () => {
  it('formats integer cents exactly, including large amounts', () => {
    expect(formatAmount(1)).toBe('0.01')
    expect(formatAmount(100)).toBe('1.00')
    expect(formatAmount(123_456_789_01)).toBe('123456789.01')
  })

  it('transliterates SEPA text to the EPC character set', () => {
    expect(sepaText('Müller & Söhne — Straße 5')).toBe('Muller Sohne Strasse 5')
    expect(sepaText('Señor Pérez, S.L.')).toBe('Senor Perez, S.L.')
  })

  it('caps party names at 70 characters', () => {
    const long = 'A'.repeat(100)
    const out = buildPain001(input([tx('E2E-1', { creditor_name: long })]))
    expect(out).toContain(`<Cdtr><Nm>${'A'.repeat(70)}</Nm></Cdtr>`)
  })
})
